language: java

jdk:
 - oraclejdk8

before_install:
 - chmod +x publishJavadoc.sh

script:
 - ./gradlew clean assemble check --stacktrace

after_success:
 - ./gradlew jacocoTestReport coveralls --stacktrace
 - ./publishJavadoc.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    secure: HA2+DFURcrXZFI+oDOotxXKdqBUFfYjel/jFKUOXTPZUmwMafRusYDMBy93xVFoYFSmYq+KsU5ty1bX3V/jGi06/NccjQaI6+2htXqcRsk37W+z9ywit+6JnkRrOmPJZVnRNyjLW1lnH3Y9dr32ol5h1S87FVyYGtP5sYdu04U4=
